services:
  web:
    image: php:8.1-apache
    container_name: test-cm-php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: >
      bash -c "
      a2enmod rewrite &&
      docker-php-ext-install pdo pdo_mysql &&
      apache2-foreground
      "

  # Base de données optionnelle si vous voulez persister des données
  db:
    image: mysql:8.0
    container_name: test-cm-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_cm
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
